//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "mqtt_ath20")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sn: String,
    #[sea_orm(column_type = "Double")]
    pub humidity: f64,
    #[sea_orm(column_type = "Double")]
    pub temperature: f64,
    pub create_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
