//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::login_token::Entity as LoginToken;
pub use super::mqtt_aht20::Entity as MqttAht20;
pub use super::mqtt_aht20_statistics::Entity as MqttAht20Statistics;
pub use super::mqtt_message::Entity as MqttMessage;
pub use super::role::Entity as Role;
pub use super::user::Entity as User;
pub use super::user_role::Entity as UserRole;
